CREATE TABLE prospects (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  code VARCHAR(100),
  name VARCHAR(100),
  address VARCHAR(255),
  external_id VARCHAR(36),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE boxes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  project VARCHAR(36) NOT NULL DEFAULT 'Murilo''s Net',
  name VARCHAR(100),
  kind ENUM('Box','Building','Property','Pop') NOT NULL,
  coords JSON NOT NULL,
  external_id VARCHAR(36),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE cables (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  project VARCHAR(36) NOT NULL DEFAULT 'Murilo''s Net',
  cable_type VARCHAR(100) NOT NULL,
  box_a VARCHAR(8) NOT NULL,
  box_b VARCHAR(8) NOT NULL,
  name VARCHAR(100) NOT NULL,
  poles JSON NOT NULL,
  external_id VARCHAR(36) NOT NULL,
  length DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  box_id BIGINT UNSIGNED,
  prospects_id BIGINT UNSIGNED,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
